### ISSUE TITLE
[fixed] 2.1.0 exports broken in 2.2.0

### ISSUE THREAD

**Issue by ajwhite** [chalk/ansi-styles#15]
Via comments on https://github.com/chalk/ansi-styles/commit/74502955deaf0eb977507757e33c52cad5a9aefa#commitcomment-16867578

```js
import ansi from 'ansi-styles';

console.log(`${ansi.colors.red.open}hello world${ansi.colors.red.close}`)
```

No longer works, with the result of

> `undefined` is not an object (evaluating `_ansiStyles2.default.colors.red`)

-----

Steps to reproduce:

1. Install 2.1.0 `npm install ansi-styles@2.1.0`
2. Use the code above
3. Update to 2.2.0 `npm install ansi-styles@2.2.0`
4. Re-run the same code, experience error

**Comment by Qix-** [comment]
Yeah this should have been a major release....

@sindresorhus best plan of action?

**Comment by Qix-** [comment]
Version 2.2.0 has been unpublished. We'll do a major bump sometime tomorrow.

Thanks for bringing this to our attention @ajwhite :+1:

**Comment by ajwhite** [comment]
Thanks for the quick recovery!

**Comment by Qix-** [comment]
![ninja-fail_o_588896](https://cloud.githubusercontent.com/assets/885648/14089074/c7c07232-f4e7-11e5-9285-370fccd3b43d.gif)

**Comment by hulbert** [comment]
So you are aware, unpublishing breaks builds that have used shrinkwrap to pin to `2.2.0`.

**Comment by Qix-** [comment]
@hulbert unpublishing breaks a lot of things, though it was necessary in this case I believe. Our next release will be 3.0.0 anyway.

Would you or @sindresorhus be willing to write some steps on how to fix the webpack issue if others are facing it? I've not used webpack personally.

---

Sorry if this inconvenienced anyone.

**Comment by sindresorhus** [comment]
@hulbert The 2.2.0 version was broken. So I don't really see how not unpublishing would have helped when it's pinned?

**Comment by sindresorhus** [comment]
Reopening for discovery.

-

I did a 2.3.1 patch release with the content of the old 2.1.0, just in case someone already upped it to `^2.2.0`.

**Comment by Qix-** [comment]
## Post Mortem

2.2.0 was actually released on Feb 21. Some breaking changes that were finally merged (ref #13) were sitting in master until we wanted to do a major version bump. However these changes were inadvertently released in 2.2.0 when the next release should have been 3.0.0 (minor bump instead of a major bump).

Since chalk wasn't affected by the otherwise breaking changes (this was by-design), but other projects that use `ansi-styles` might have been, the breaking release 2.2.0 went unnoticed until now.

This is also due to the fact the 'breaking' changes were not buggy code, but intentional changes meant for a major version bump, hence why tests still passed on travis and thus why we were not notified of any breaking CI runs.

As Sindre mentioned, we went ahead and still did a 2.2.1 patch release despite the unpublishing of 2.2.0, for those users that had already bumped their package.json dependencies to `^2.2.0`.

Those experiencing errors related to `ansi-styles` should clear out their `node_modules/` directory re-run `npm install` - the problem should resolve itself.

Sorry again to anyone affected by this!

**Comment by laurelnaiad** [comment]
... and remember to do the same with jspm if you're using it, where this was hitting our project

```
jspm cache-clear
```

**Comment by laurelnaiad** [comment]
>  unpublishing breaks a lot of things, though it was necessary in this case I believe

Why was it necessary? Why not publish the version you intended at 2.2.1, and let everybody move forward? If they're referencing a broken 2.2.0 then they can update. I'm not trying to be a PITA about it, just curious where the necessity of unpublishing comes in as opposed to just publishing 2.2.1.

**Comment by Qix-** [comment]
@laurelnaiad you're correct. Sindre and I discussed it more after the fact and we agree that a patch would have been better. A lesson for the future :+1:

**Comment by laurelnaiad** [comment]
Ok, it's not a big deal, just wanted to understand. Thanks! :)

**Comment by Qix-** [comment]
Thanks for the feedback :dancer:

**Comment by laurelnaiad** [comment]
the dancer emoticon should be bigger so we can see her fabulous red dress

**Comment by tlrobinson** [comment]
Seriously, unpublishing should be reserved for exceptional cases. I'm not sure how you thought this was a good idea less than a week after the left-pad incident.

**Comment by bradvogel** [comment]
PLEASE don't unpublish! This causes disasters downstream. NO, NO!

**Comment by Qix-** [comment]
@tlrobinson We didn't unpublish the module, just that particular version. Quite different.

@bradvogel We're aware. :+1:
