### ISSUE TITLE
Ambiguous error when keyword doesn't exist

### ISSUE THREAD

**Issue by Qix-** [chalk/ansi-styles#36]
A strange error is thrown if the argument thrown to `keyword()` doesn't exist.

```
> chalk.keyword('blackfsdfsd')

16:00:00.000 index.js:16 Uncaught TypeError: Cannot read property '0' of undefined
    at /src/chalk/chalk/node_modules/ansi-styles/index.js:16:39
    at Function.<anonymous> (/src/chalk/chalk/index.js:76:63)
    at eval (eval at buildStyle (/src/chalk/chalk/templates.js:68:22), <anonymous>:1:7)
    at buildStyle (/src/chalk/chalk/templates.js:68:22)
    at tmp.replace (/src/chalk/chalk/templates.js:111:16)
    at String.replace (<anonymous>)
    at module.exports (/src/chalk/chalk/templates.js:98:6)
    at chalkTag (/src/chalk/chalk/index.js:214:9)
    at Chalk.chalk.template (/src/chalk/chalk/index.js:36:20)
    at Object.<anonymous> (/src/chalk/chalk/test-tmpl.js:9:14)
```

**Comment by danthegoodman** [comment]
[`wrapAnsi16m`](https://github.com/chalk/ansi-styles/blob/master/index.js#L15] seems to be the culprit here. Should it throw an error if the `fn` returns undefined or should the error be thrown inside of the `color-conversion` library when it [converts a keyword to rgb](https://github.com/Qix-/color-convert/blob/master/conversions.js#L203)?

@Qix- I'm happy to do a PR to either project, but I felt like I should run it by you first.

**Comment by sindresorhus** [comment]
I think it should be an error in `color-conversion`, but I'll let @Qix- make the final call.

**Comment by Qix-** [comment]
I think it's correct that `color-convert` returns `null` if the keyword doesn't exist - in which case, `ansi-styles` should throw.

cc @danthegoodman - feel free :) It'd be super appreciated.

**Comment by danthegoodman** [comment]
I'm happy with the solution implemented for `color.ansi16m.keyword`, since it will cleanly handle other functions if they decide to start returning null or undefined. 

Unfortunately, the error handling for `color.ansi256.keyword` and `color.ansi.keyword` is specific to the keyword function. These functions caused the same ambiguous error deeper within the `color-convert` library.

When I had only investigated the `ansi16m` fix, I was in agreement with @Qix-, that the fix should be in this project. Now that i've seen the error get thrown from within there, I'm learning a bit more in line with @sindresorhus that the conversion library receive a patch instead.

**Comment by sindresorhus** [comment]
> I think it's correct that color-convert returns null if the keyword doesn't exist - in which case, ansi-styles should throw.

@Qix- I disagree. Incorrect input should throw, not silently return null`. That's what the user would expect, and how Node.js and browser APIs work too. Can you please reconsider?

**Comment by sindresorhus** [comment]
> My only hangup with it is that none of the other methods throw for incorrect input.

They should throw too, though.

> since there are usecases where merely checking if a keyword is valid is useful.

Then there should be a separate method to check whether a keyword is valid. Please make the common-case user-friendly.

> Unless, that is, you want to start advocating for exceptions to be used as flow control.

This is not about flow control. It's about input validation and not silently accept invalid input.

**Comment by Qix-** [comment]
So I should add input validation to every single conversion method?

**Comment by sindresorhus** [comment]
Yes

**Comment by sindresorhus** [comment]
Closing in favor of https://github.com/Qix-/color-convert/issues/72.
